name: gcm-filters-docs
dependencies:
  - python=3.8
  - numpy
  - scipy
  - xarray
  - matplotlib
  - numpydoc
  - sphinx
  - ipython
  - nbconvert
  - nbformat
  - ipykernel # not strictly necessary but this is nice to run notebooks in this env to test
  - pandoc
  - pip
  - pip:
    - jupyter_client
    - sphinx-book-theme
    - sphinx-copybutton
    - sphinxcontrib-srclinks
    - myst-parser
    - myst-nb
